export const AppRoutes = {
  root: "/",
  contact: "contact",
  about: "about",
  termAndCondition: "tearm-and-conditions",
  auth: "auth",
  developers: "developers",
  authSignup: "/auth/signup",
  authVerifyEmail: "/auth/verify-email",
  authForgotPassword: "/auth/forgot-password",
  authSignout: "signout",
  user: "user",
  userPosts: "/user/posts",
  userVideos: "/user/videos",
  userProfile: "/user/profile",
  userFriends: "/user/friends",
  userPhotos: "/user/photos",
  userSettings: "/user/settings",
  admin: "admin",
  adminUser: "/admin/users",
  adminDesignation: "/admin/designations",
  adminSkill: "/admin/skills",
  adminPosts: "/admin/posts",
  adminProfile: "/admin/profile",
  adminRole: "/admin/roles",
  adminSetting: "/admin/settings",
};
